### ISSUE TITLE
cannot run deployer with FLASK_DEBUG: 1

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renga#25] opened 2017-09-01 08:59 UTC
when adding `FLASK_DEBUG: 1` to `docker-compose.yml` the deployer fails to start

**Comment by leafty** [comment] 2017-09-13 09:09
Duplicate of https://github.com/SwissDataScienceCenter/renga-deployer/issues/25

**Closed** 2017-09-13 10:24 UTC
